services:
  mysql:
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/mysql-config.cnf:/config/config.cnf
    mem_limit: 512m
    networks:
      - mysqlnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=pos-password
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=pos-password

  mysql-test:
    image: mysql:8.0
    container_name: mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: test-password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test-user
      MYSQL_PASSWORD: test-password
    ports:
      - "3307:3306"
    volumes:
      - mysql-test:/var/lib/mysql

  mysql-admin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: mysql-phpmyadmin
    ports:
      - "8001:80"
    mem_limit: 512m
    networks:
      - mysqlnetwork
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pos-password

  consul:
    restart: always
    container_name: consul
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data
    networks:
      - consulnetwork
    command: agent -dev -client=0.0.0.0

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/consul-template/templates
      - ./nginx/conf.data:/etc/nginx/conf.d
    depends_on:
      - consul
    networks:
      - consulnetwork
    command: ["nginx", "-g", "daemon off;"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmqnetwork

  consul-template:
    restart: always
    build:
      context: .
      dockerfile: ./consul-template/Dockerfile
    container_name: consul-template
    environment:
      CONSUL_HTTP_ADDR: "http://consul:8500"
    volumes:
      - ./consul-template/config:/etc/consul-template
      - ./nginx/templates:/etc/consul-template/templates
      - ./nginx/conf.data:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - consulnetwork
    depends_on:
      - consul
      - nginx
    command:
      ["consul-template", "-config", "/etc/consul-template/consul-template.hcl"]

volumes:
  mysql:
    driver: local
  mysql-test:

networks:
  mysqlnetwork:
    driver: bridge
  consulnetwork:
    driver: bridge
  rabbitmqnetwork:
    driver: bridge
