# To run this docker compose file, run the following command: docker-compose -f docker/docker-compose.yml up --build -d

services:
  mysql:
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
      - ./mysql-config.cnf:/config/config.cnf
    mem_limit: 512m
    networks:
      - mysqlnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=pos-password
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=pos-password

  mysql-admin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: mysql-phpmyadmin
    ports:
      - "8001:80"
    mem_limit: 512m
    networks:
      - mysqlnetwork
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pos-password

  consul:
    restart: always
    container_name: consul
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data
    networks:
      - consul-network
    command: agent -dev -client=0.0.0.0

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/consul-template/templates
      - ./nginx/conf.data:/etc/nginx/conf.d
    depends_on:
      - consul
    networks:
      - consul-network
    command: ["nginx", "-g", "daemon off;"]

  consul-template:
    restart: always
    build:
      context: .
      dockerfile: ./consul-template/Dockerfile
    container_name: consul-template
    environment:
      CONSUL_HTTP_ADDR: "http://consul:8500"
    volumes:
      - ./consul-template/config:/etc/consul-template
      - ./nginx/templates:/etc/consul-template/templates
      - ./nginx/conf.data:/etc/nginx/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - consul-network
    depends_on:
      - consul
      - nginx
    command:
      ["consul-template", "-config", "/etc/consul-template/consul-template.hcl"]

  # Removing registrator for now as it is using Docker Image manifest that is deprecated
  # registrator:
  #   image: gliderlabs/registrator:latest
  #   command: -internal consul://consul:8500
  #   network_mode: host
  #   environment:
  #     - CONSUL_HTTP_ADDR=consul:8500
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock

  auth-service:
    build:
      context: ..
      dockerfile: ./services/auth-service/docker/Dockerfile
    environment:
      - DB_HOST=mysql
      - CONSUL_ADDRESS=consul:8500
    ports:
      - "4001:4001"
    networks:
      - consul-network
      - mysqlnetwork

volumes:
  mysql:
    driver: local

networks:
  mysqlnetwork:
    driver: bridge
  consul-network:
    driver: bridge
