# Stage 1: Base setup
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Stage 2: Install dependencies
FROM base AS development
# Copy the source code
WORKDIR /usr/src/app

# Copy workspace configuration and lockfile to leverage Docker cache
COPY pnpm-lock.yaml package.json pnpm-workspace.yaml ./
COPY .npmrc ./
COPY nx.json ./

COPY . /usr/src/app

# Install all dependencies (including dev dependencies)
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

# Expose the development port
EXPOSE 4002

# Command to run the service in development mode
CMD ["pnpm", "nx", "dev", "@pos/products"]
